/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.controller.ui.*;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class Main extends Application {

    private Parent EurobisioaUI;

    private Stage stage;

    private Scene sceneHasiera;
    private Scene sceneHerrialdeaHautatu;
    private Scene sceneErrorea;
    private Scene sceneTop3;
    private Scene sceneHerrialdeBozkatu;
    private Parent herrialdeaHautatuUI;
    private Parent hasieraUI;
    private Parent erroreaUI;
    private Parent herrialdeaBozkatuUI;
    private Parent top3UI;
    private HasieraKud hasieraKud;
    private HerrialdeaHautatuKud herrialdeaHautatuKud;
    private ErroreaKud erroreaKud;
    private HerrialdeaBozkatuKud herrialdeaBozkatuKud;
    private Top3Kud top3Kud;


    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        pantailakKargatu();

        stage.setTitle("EUROBISIOAFX");
        stage.setScene(sceneHasiera);
        stage.show();
    }

    //ESZENA GUZTIAK
    public void hasieraErakutsi(){
        stage.setScene(sceneHasiera);
    }

    public void herrialdeakHautatuErakutsi(){
        stage.setScene(sceneHerrialdeaHautatu);
    }

    public void erroreaErakutsi(){
        stage.setScene(sceneErrorea);
    }

    public void herrialdeaBozkatuErakutsi(){stage.setScene(sceneHerrialdeBozkatu);}

    public void top3Erakutsi(){stage.setScene(sceneTop3);}


    //PANTAILA KARGATZEKO
    private void pantailakKargatu() throws IOException {

        FXMLLoader loaderHasiera = new FXMLLoader(getClass().getResource("/hasiera.fxml"));
        hasieraUI = (Parent) loaderHasiera.load();
        hasieraKud = loaderHasiera.getController();
        hasieraKud.setMainApp(this);
        sceneHasiera=new Scene(hasieraUI);

        FXMLLoader loaderHerrialdeaHautatu = new FXMLLoader(getClass().getResource("/herrialdeaHautatu.fxml"));
        herrialdeaHautatuUI = (Parent) loaderHerrialdeaHautatu.load();
        herrialdeaHautatuKud = loaderHerrialdeaHautatu.getController();
        herrialdeaHautatuKud.setMainApp(this);
        sceneHerrialdeaHautatu=new Scene(herrialdeaHautatuUI);

        FXMLLoader loaderErrorea = new FXMLLoader(getClass().getResource("/errorea.fxml"));
        erroreaUI = (Parent) loaderErrorea.load();
        erroreaKud = loaderErrorea.getController();
        erroreaKud.setMainApp(this);
        sceneErrorea=new Scene(erroreaUI);

        FXMLLoader loaderHerrialdeaBozkatu = new FXMLLoader(getClass().getResource("/herrialdeaBozkatu.fxml"));
        herrialdeaBozkatuUI = (Parent) loaderHerrialdeaBozkatu.load();
        herrialdeaBozkatuKud = loaderHerrialdeaBozkatu.getController();
        herrialdeaBozkatuKud.setMainApp(this);
        sceneHerrialdeBozkatu=new Scene(herrialdeaBozkatuUI);

        FXMLLoader loaderTop3 = new FXMLLoader(getClass().getResource("/top3.fxml"));
        top3UI = (Parent) loaderTop3.load();
        top3Kud = loaderTop3.getController();
        top3Kud.setMainApp(this);
        sceneTop3=new Scene(top3UI);
    }

    //GET-AK
    public ErroreaKud getErroreaKud(){
        return this.erroreaKud;
    }

    public HerrialdeaBozkatuKud getHerrialdeaBozkatuKud(){
        return this.herrialdeaBozkatuKud;
    }

    public Top3Kud getTop3Kud(){return this.top3Kud;}

}
